### ISSUE TITLE
Unexpected defaults on CentOS/RHEL 7 for non-MariaDB installations

### ISSUE THREAD

**Issue by fraenki** [fraenki/puppet-galera#120]
On CentOS 7 puppetlabs-mysql will default to MariaDB, which results in some MariaDB-specific configurations/paths, even when using Percona XtraDB or Codership Galera Cluster.

This is mostly a cosmetic issue, the MySQL server is still fully functional.

We may overwrite some puppetlabs-mysql parameters to fix this.

**Comment by fraenki** [comment]
The upcoming version 2.0.0 of this module allows to provide working default values for all vendors.
The module will provide default values, i.e.

```
galera::codership::default_options:
  mysqld:
    log-error: '/var/log/mysqld.log'
    pid-file: '/var/run/mysqld/mysqld.pid'
```

Users should not use `$default_options` to set custom values, but instead override values by using the `$override_options` parameter, which will always take precedence.
